name: GitHub Actions Saucedemo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
      - name: Black and Flake8
        uses: ricardochaves/python-lint@v1.4.0
        with:
            python-root-list: "python_alelo tests"
            use-pylint: false
            use-pycodestyle: false
            use-flake8: true
            use-black: true
            use-mypy: false
            use-isort: false
            extra-pylint-options: ""
            extra-pycodestyle-options: ""
            extra-flake8-options: "-count --benchmark --ignoreE501"
            extra-black-options: ". -s"
            extra-mypy-options: ""
            extra-isort-options: ""
      - name: Update repo
        run: sudo apt-get update
      - name: Install software
        run: sudo apt-get install -y chromium-browser
      - name: Chromium version
        run: chromium-browser --version
      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Instal dependencies
        run: poetry install
      - name: Run pytest
        run: poetry run pytest
